#!/usr/bin/env bash

set -Eeuo pipefail

readonly DEFAULT_RULE_DIR="/etc/polkit-1/rules.d"
readonly RULE_NAME="00-current-user-no-auth.rules"
readonly EXIT_CONFLICT=3
readonly EXIT_USAGE=64

# Prints command usage.
#
# Args:
#   None.
# Returns:
#   0 after printing usage information.
# Raises:
#   None.
usage() {
    cat <<'EOF_USAGE'
Usage: toggle-polkit-prompts [on|off|toggle|status|help]

Commands:
  on      Disable Polkit authentication prompts for the active local user.
  off     Restore normal Polkit authentication prompts.
  toggle  Switch between on and off. This is the default.
  status  Show the current state without changing anything.
  help    Show this help text.

This script does not modify sudo configuration.
EOF_USAGE
}

# Resolves the directory containing the managed Polkit rule.
#
# Args:
#   None.
# Returns:
#   Prints the rule directory path.
# Raises:
#   Exits through Bash parameter validation if test mode lacks a rule directory.
resolve_rule_dir() {
    if [[ "${POLKIT_TOGGLE_TEST_MODE:-0}" == "1" ]]; then
        printf '%s\n' "${POLKIT_TOGGLE_RULE_DIR:?POLKIT_TOGGLE_RULE_DIR is required in test mode}"
        return
    fi

    printf '%s\n' "$DEFAULT_RULE_DIR"
}

# Resolves the account that should receive automatic Polkit authorization.
#
# Args:
#   None.
# Returns:
#   Prints the target username.
# Raises:
#   Propagates an id(1) failure if the current username cannot be resolved.
# Notes:
#   When the whole script is launched with sudo, SUDO_USER identifies the
#   original desktop user. Test mode can inject a deterministic username.
resolve_target_user() {
    if [[ "${POLKIT_TOGGLE_TEST_MODE:-0}" == "1" && -n "${POLKIT_TOGGLE_TEST_USER:-}" ]]; then
        printf '%s\n' "$POLKIT_TOGGLE_TEST_USER"
        return
    fi

    if [[ $EUID -eq 0 && -n "${SUDO_USER:-}" && "$SUDO_USER" != "root" ]]; then
        printf '%s\n' "$SUDO_USER"
        return
    fi

    id -un
}

# Escapes a string for use inside a JavaScript double-quoted literal.
#
# Args:
#   $1: Raw string to escape.
# Returns:
#   Prints the escaped string without a trailing newline.
# Raises:
#   None.
js_escape() {
    local value="$1"

    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}
    value=${value//$'\r'/\\r}
    printf '%s' "$value"
}

# Renders the exact Polkit rule owned by this script.
#
# Args:
#   $1: Target username.
# Returns:
#   Prints the complete JavaScript rule.
# Raises:
#   Propagates failures from username escaping or output generation.
render_rule() {
    local target_user="$1"
    local escaped_user

    escaped_user="$(js_escape "$target_user")"

    cat <<EOF_RULE
// Managed by toggle-polkit-auth.sh. Do not edit this file manually.
polkit.addRule(function(action, subject) {
    if (subject.user == "$escaped_user" &&
        subject.local &&
        subject.active) {
        return polkit.Result.YES;
    }
});
EOF_RULE
}

# Renders the exact rule produced by the earlier version of this script.
#
# Args:
#   $1: Target username.
# Returns:
#   Prints the legacy JavaScript rule.
# Raises:
#   None.
render_legacy_rule() {
    local target_user="$1"
    local escaped_user

    escaped_user="$(js_escape "$target_user")"

    cat <<EOF_RULE
polkit.addRule(function(action, subject) {
    if (subject.user == "$escaped_user" &&
        subject.local &&
        subject.active) {
        return polkit.Result.YES;
    }
});
EOF_RULE
}

# Inspects whether a path exists without conflating absence with sudo failure.
#
# Args:
#   $1: Path to inspect.
# Returns:
#   Prints exists or absent and returns 0 when inspection itself succeeds.
# Raises:
#   Propagates privilege-helper failures so callers can fail closed.
inspect_path_state() {
    local path="$1"

    run_privileged sh -c '
        if [ -L "$1" ]; then
            printf "symlink\n"
        elif [ -e "$1" ]; then
            printf "exists\n"
        else
            printf "absent\n"
        fi
    ' sh "$path"
}

# Runs a command with root privileges when needed.
#
# Args:
#   $@: Command and arguments to execute.
# Returns:
#   The wrapped command's exit status.
# Raises:
#   Returns the privilege helper's failure status if elevation fails.
# Notes:
#   Test-only overrides are honored only when POLKIT_TOGGLE_TEST_MODE=1.
run_privileged() {
    if [[ "${POLKIT_TOGGLE_TEST_MODE:-0}" == "1" ]]; then
        if [[ "${POLKIT_TOGGLE_TEST_FORCE_SUDO:-0}" == "1" ]]; then
            local test_sudo="${POLKIT_TOGGLE_TEST_SUDO:?POLKIT_TOGGLE_TEST_SUDO is required when forcing sudo in test mode}"
            "$test_sudo" "$@"
        else
            "$@"
        fi
        return
    fi

    if [[ $EUID -eq 0 ]]; then
        "$@"
    else
        sudo -- "$@"
    fi
}

# Validates prerequisites before any command operates on the rule.
#
# Args:
#   $1: Rule directory path.
#   $2: Target username.
# Returns:
#   0 when prerequisites are satisfied.
# Raises:
#   Returns 1 if the directory, target account, or sudo command is unavailable.
validate_environment() {
    local rule_dir="$1"
    local target_user="$2"

    if [[ ! -d "$rule_dir" ]]; then
        printf 'Error: Polkit rule directory does not exist: %s\n' "$rule_dir" >&2
        return 1
    fi

    if [[ "${POLKIT_TOGGLE_TEST_MODE:-0}" == "1" ]]; then
        return 0
    fi

    if ! id -u "$target_user" >/dev/null 2>&1; then
        printf 'Error: target user does not exist: %s\n' "$target_user" >&2
        return 1
    fi

    if [[ $EUID -ne 0 ]] && ! command -v sudo >/dev/null 2>&1; then
        printf 'Error: sudo is required to modify %s\n' "$rule_dir" >&2
        return 1
    fi
}

# Determines the current managed state.
#
# Args:
#   $1: Rule file path.
#   $2: Target username.
# Returns:
#   Prints enabled, disabled, legacy, or conflict.
# Raises:
#   Returns non-zero if the rule path cannot be inspected or read safely.
# Notes:
#   Inspection is privileged because current Ubuntu releases may restrict
#   traversal of /etc/polkit-1/rules.d to root and the polkitd group.
get_state() {
    local rule_file="$1"
    local target_user="$2"
    local path_state
    local actual
    local managed
    local legacy

    if ! path_state="$(inspect_path_state "$rule_file")"; then
        printf 'Error: unable to inspect Polkit rule path: %s\n' "$rule_file" >&2
        return 1
    fi

    if [[ "$path_state" == "absent" ]]; then
        printf 'enabled\n'
        return 0
    fi

    if [[ "$path_state" == "symlink" ]]; then
        printf 'conflict\n'
        return 0
    fi

    if [[ "$path_state" != "exists" ]]; then
        printf 'Error: unexpected inspection result for: %s\n' "$rule_file" >&2
        return 1
    fi

    if ! actual="$(run_privileged cat -- "$rule_file")"; then
        printf 'Error: unable to read Polkit rule: %s\n' "$rule_file" >&2
        return 1
    fi

    managed="$(render_rule "$target_user")"
    legacy="$(render_legacy_rule "$target_user")"

    if [[ "$actual" == "$managed" ]]; then
        printf 'disabled\n'
    elif [[ "$actual" == "$legacy" ]]; then
        printf 'legacy\n'
    else
        printf 'conflict\n'
    fi
}

# Atomically installs the generated rule in the Polkit rules directory.
#
# Args:
#   $1: Rule directory path.
#   $2: Final rule file path.
#   $3: Target username.
# Returns:
#   0 after the rule has been written, permissioned, and atomically renamed.
# Raises:
#   Returns a non-zero status if temporary-file creation, writing, chmod, or
#   rename fails. A best-effort cleanup removes the temporary file on failure.
write_rule_atomic() {
    local rule_dir="$1"
    local rule_file="$2"
    local target_user="$3"
    local temp_file=""

    temp_file="$(run_privileged mktemp "$rule_dir/.toggle-polkit-auth.XXXXXX")" || return 1

    if ! render_rule "$target_user" | run_privileged tee "$temp_file" >/dev/null; then
        run_privileged rm -f -- "$temp_file" >/dev/null 2>&1 || true
        return 1
    fi

    if ! run_privileged chmod 0644 "$temp_file"; then
        run_privileged rm -f -- "$temp_file" >/dev/null 2>&1 || true
        return 1
    fi

    if ! run_privileged mv -f -- "$temp_file" "$rule_file"; then
        run_privileged rm -f -- "$temp_file" >/dev/null 2>&1 || true
        return 1
    fi
}

# Enables automatic authorization for all Polkit actions for the target user.
#
# Args:
#   $1: Rule directory path.
#   $2: Rule file path.
#   $3: Target username.
# Returns:
#   0 when enabled or already enabled, EXIT_CONFLICT on an unexpected file.
# Raises:
#   Propagates filesystem or privilege errors from rule installation.
enable_bypass() {
    local rule_dir="$1"
    local rule_file="$2"
    local target_user="$3"
    local state

    state="$(get_state "$rule_file" "$target_user")"
    case "$state" in
        disabled)
            printf 'Authentication prompts: DISABLED (already disabled)\n'
            printf 'User: %s\n' "$target_user"
            return 0
            ;;
        legacy)
            write_rule_atomic "$rule_dir" "$rule_file" "$target_user"
            printf 'Authentication prompts: DISABLED (migrated legacy rule)\n'
            printf 'User: %s\n' "$target_user"
            ;;
        conflict)
            printf 'Authentication prompts: CONFLICT\n' >&2
            printf 'Refusing to overwrite unexpected file: %s\n' "$rule_file" >&2
            return "$EXIT_CONFLICT"
            ;;
        enabled)
            write_rule_atomic "$rule_dir" "$rule_file" "$target_user"
            printf 'Authentication prompts: DISABLED\n'
            printf 'User: %s\n' "$target_user"
            ;;
    esac
}

# Restores normal Polkit authentication by removing only this script's rule.
#
# Args:
#   $1: Rule file path.
#   $2: Target username.
# Returns:
#   0 when restored or already restored, EXIT_CONFLICT on an unexpected file.
# Raises:
#   Propagates filesystem or privilege errors from rule removal.
disable_bypass() {
    local rule_file="$1"
    local target_user="$2"
    local state

    state="$(get_state "$rule_file" "$target_user")"
    case "$state" in
        enabled)
            printf 'Authentication prompts: ENABLED (already enabled)\n'
            return 0
            ;;
        conflict)
            printf 'Authentication prompts: CONFLICT\n' >&2
            printf 'Refusing to remove unexpected file: %s\n' "$rule_file" >&2
            return "$EXIT_CONFLICT"
            ;;
        disabled|legacy)
            run_privileged rm -- "$rule_file"
            printf 'Authentication prompts: ENABLED\n'
            ;;
    esac
}

# Prints the current state without modifying the filesystem.
#
# Args:
#   $1: Rule file path.
#   $2: Target username.
# Returns:
#   0 for a known enabled or disabled state, EXIT_CONFLICT otherwise.
# Raises:
#   Propagates state-inspection failures.
show_status() {
    local rule_file="$1"
    local target_user="$2"
    local state

    state="$(get_state "$rule_file" "$target_user")"
    case "$state" in
        enabled)
            printf 'Authentication prompts: ENABLED\n'
            ;;
        disabled)
            printf 'Authentication prompts: DISABLED\n'
            printf 'User: %s\n' "$target_user"
            ;;
        legacy)
            printf 'Authentication prompts: DISABLED (legacy rule detected)\n'
            printf 'User: %s\n' "$target_user"
            ;;
        conflict)
            printf 'Authentication prompts: CONFLICT\n' >&2
            printf 'Unexpected file occupies the managed path: %s\n' "$rule_file" >&2
            return "$EXIT_CONFLICT"
            ;;
    esac
}

# Executes the requested command.
#
# Args:
#   $@: Zero or one command argument.
# Returns:
#   0 on success, EXIT_USAGE for invalid arguments, or a command-specific error.
# Raises:
#   Propagates validation, privilege, state-inspection, and filesystem failures.
main() {
    local command="${1:-toggle}"
    local rule_dir
    local rule_file
    local target_user
    local state

    if (( $# > 1 )); then
        usage >&2
        return "$EXIT_USAGE"
    fi

    case "$command" in
        help|-h|--help)
            usage
            return 0
            ;;
        on|off|toggle|status)
            ;;
        *)
            printf 'Error: unsupported command: %s\n\n' "$command" >&2
            usage >&2
            return "$EXIT_USAGE"
            ;;
    esac

    rule_dir="$(resolve_rule_dir)"
    rule_file="$rule_dir/$RULE_NAME"
    target_user="$(resolve_target_user)"
    validate_environment "$rule_dir" "$target_user"

    if [[ "$command" != status ]]; then
        state="$(get_state "$rule_file" "$target_user")"
        if [[ "$state" == conflict ]]; then
            show_status "$rule_file" "$target_user"
            return "$EXIT_CONFLICT"
        fi
        show_status "$rule_file" "$target_user"
        printf '%s\n' 'This bypass authorizes all Polkit actions for the active local user, including Polkit-mediated settings and package actions.'
        printf '%s\n' 'sudo, login and lock-screen prompts, app-specific passwords, other users, and remote or inactive sessions are unaffected.'
        if [[ "$command" == toggle ]]; then
            if [[ "$state" == enabled ]]; then command=on; else command=off; fi
        fi
        if [[ "$command" == on && "$state" == enabled ]] || [[ "$command" == off && "$state" != enabled ]]; then
            printf 'Apply %s? [y/N]: ' "$command"
            read -r answer || return 1
            case "$answer" in y|Y|yes|YES) ;; *) printf '%s\n' 'Canceled; no changes made.'; return 0 ;; esac
        else
            printf '%s\n' 'Requested state is already active; no changes made.'
            return 0
        fi
    fi

    case "$command" in
        on)
            enable_bypass "$rule_dir" "$rule_file" "$target_user"
            ;;
        off)
            disable_bypass "$rule_file" "$target_user"
            ;;
        status)
            show_status "$rule_file" "$target_user"
            ;;
        toggle)
            state="$(get_state "$rule_file" "$target_user")"
            case "$state" in
                enabled)
                    enable_bypass "$rule_dir" "$rule_file" "$target_user"
                    ;;
                disabled|legacy)
                    disable_bypass "$rule_file" "$target_user"
                    ;;
                conflict)
                    printf 'Authentication prompts: CONFLICT\n' >&2
                    printf 'Refusing to modify unexpected file: %s\n' "$rule_file" >&2
                    return "$EXIT_CONFLICT"
                    ;;
            esac
            ;;
    esac
}

main "$@"
